-- 코드를 입력하세요
WITH PR_TABLE AS
(SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, B.PRICE * S.SALES AS PR
FROM BOOK B JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, P.CATEGORY, SUM(P.PR) TOTAL_SALES
FROM PR_TABLE P JOIN AUTHOR A ON P.AUTHOR_ID = A.AUTHOR_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID ASC, P.CATEGORY DESC