# SELECT HISTORY_ID,
#     CASE
#         WHEN DD >= 90
#         THEN round(C.DAILY_FEE * DD * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = "90일 이상" AND CAR_TYPE = "트럭")) / 100)
#         WHEN DD >= 30
#         THEN round(C.DAILY_FEE * DD * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = "30일 이상" AND CAR_TYPE = "트럭")) / 100)
#         WHEN DD >= 7
#         THEN round(C.DAILY_FEE * DD * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = "7일 이상" AND CAR_TYPE = "트럭")) / 100)
#         ELSE round(C.DAILY_FEE * DD)
#     END FEE
# FROM (
#     SELECT B.HISTORY_ID, A.DAILY_FEE, DATEDIFF(B.END_DATE, B.START_DATE) + 1 DD
#     FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = '트럭') A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
#     ) C
# ORDER BY FEE DESC, HISTORY_ID DESC

# 날 차이 구해서 90일 이상 이것들 만들어 논 테이블 구성
WITH VA AS(
    SELECT A.HISTORY_ID, A.CAR_ID, B.DAILY_FEE, B.CAR_TYPE, DATEDIFF(END_DATE, START_DATE) + 1 DD,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90
            THEN "90일 이상"
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30
            THEN "30일 이상"
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7
            THEN "7일 이상"
            ELSE "7일 이하"
        END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = "트럭"
    )

SELECT A.HISTORY_ID, ROUND(IF(discount_rate, (100 - discount_rate) / 100, 1) * DD * DAILY_FEE) FEE
FROM VA A LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE AND A.DURATION_TYPE = B.DURATION_TYPE
ORDER BY FEE DESC, A.HISTORY_ID DESC
# SELECT *
# FROM VA A LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE AND A.DURATION_TYPE = B.DURATION_TYPE
