-- 코드를 입력하세요

# 완료된 중고금액이 70만원 이상
# 보드를 유저별로 그룹하고, Price의 합을 구한다. 단 Status가 Done 인경우
SELECT A.USER_ID, A.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER A JOIN 
(
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) B
ON A.USER_ID = B.WRITER_ID
ORDER BY TOTAL_SALES
