-- 코드를 입력하세요
# 가장 비싼 제품 구하기
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT * , RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RK
    FROM FOOD_PRODUCT) A
WHERE A.CATEGORY IN ('과자', '국','김치', '식용유') AND RK = 1
ORDER BY MAX_PRICE DESC